// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID        string  `json:"id"`
	URL       string  `json:"url"`
	Title     *string `json:"title,omitempty"`
	Content   *string `json:"content,omitempty"`
	OwnerID   string  `json:"ownerId"`
	CreatedAt string  `json:"createdAt"`
}
