version: "3.9"

services:
  backend:
    build:
      context: ./trendpulse-backend
      dockerfile: Dockerfile
    working_dir: /app/cmd/api
    command: ["/app/bin/api"]
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: ./trendpulse-backend
      dockerfile: Dockerfile
    working_dir: /app/cmd/worker
    command: ["/app/bin/worker"]
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: trendpulse
      DB_PORT: 5432
    ports:
      - "5432:5432"
