version: "3.9"

services:
  backend:
    build:
      context: ./trendpulse-backend
      dockerfile: Dockerfile
    working_dir: /app
    command: ["/app/bin/api"]
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: trendpulse
      DB_PORT: "5432"
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: ./trendpulse-backend
      dockerfile: Dockerfile
    working_dir: /app
    command: ["/app/bin/worker"]
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: trendpulse
      DB_PORT: "5432"
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: trendpulse
    ports:
      - "5432:5432"
